### PR TITLE
Mobile devices bug fixed

### PR DESCRIPTION
**Pull request by Prithivi333**
Removed the user-info custom scss class to fix the width of the user container

### CODE REVIEW

**Comment by ghost** [comment]
On it, I'll review the changes right away.

**Review by ghost — APPROVED** [review]
Nailed it! Excellent job @Prithivi333! You can now merge the PR.

**Comment by Prithivi333** [comment]
Fixed mobile display bug

**Review by Prithivi333 — COMMENTED** [review]
Verify and approve the changes

**Pull request merged**
